#ifndef CONSTANT_H
#define CONSTANT_H

#define ALL_PRODUCT_ID "-999"
#define ALL_USERS "-999"
#define DELETE_QUANTITY -999
#define IGNORE_UPDATE_PRICE -999
#define IGNORE_UPDATE_TITLE "-999"
#define IGNORE_UPDATE_QUANTITY -999
#define DELETE_QUANTITY_STR "-999"
#define IGNORE_UPDATE_PRICE_STR "-999"
#define IGNORE_UPDATE_QUANTITY_STR "-999"
#endif